development:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: teachers_pet
  pool: 5
  username: root
  password: 
test:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: teachers_pet
  pool: 5
  username: root
  password: 

production:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: teachers_pet
  pool: 5
  username: root
  password: 
